// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"go_di/static/implementations"
)

// Injectors from wire.go:

func InitializeServer() *implementations.HTTPServer {
	iLogger := implementations.ProvideLogger()
	httpServer := implementations.ProvideHTTPServer(iLogger)
	return httpServer
}
